/**
 * `@image-ultra/core` — the stable, semver-covered API: edit state, loading, rendering / export,
 * the editor store, filters and looks, and the types they use (DECISIONS #107). Helpers used only by
 * `@image-ultra/react` live in `@image-ultra/core/internal`.
 */
export {
  /* Loading */
  loadImage,
  ImageLoadError,
  detectImageFormat,
  type ImageLoadErrorCode,
  type LoadImageOptions,
  type ImageFormat,
  type ImageSource,
  type LoadedImage,

  /* Edit state (serializable JSON) */
  EDIT_STATE_VERSION,
  EditStateError,
  MAX_OUTPUT_SIDE,
  FINETUNE_KEYS,
  FINETUNE_RANGES,
  createEditState,
  parseEditState,
  getBeforeState,
  type EditState,
  type EditAsset,
  type RasterAsset,
  type GeometryState,
  type QuarterTurn,
  type CropShape,
  type CanvasState,
  type ResizeState,
  type FinetuneState,
  type LevelsState,
  type CurvesState,
  type CurveChannel,
  type CurvePoint,
  type FilterState,
  type Rect,
  type Point,
  type Size,

  /* Elements on the photo */
  WATERMARK_ELEMENT_ID,
  REDACT_STYLES,
  type Shape,
  type ShapeType,
  type DrawnShape,
  type LineShape,
  type RectShape,
  type EllipseShape,
  type PathShape,
  type TextShape,
  type ImageShape,
  type RedactShape,
  type WatermarkShape,
  type Paint,
  type LineCap,
  type TextAlign,
  type Redaction,
  type RedactBox,
  type RedactBrush,
  type RedactStyle,

  /* Frame, Fill and watermark */
  FRAME_STYLES,
  WATERMARK_POSITIONS,
  DEFAULT_WATERMARK,
  type FrameState,
  type FrameStyle,
  type BackgroundState,
  type WatermarkState,
  type WatermarkPosition,

  /* Filters, looks and auto-enhance */
  FILTER_PRESETS,
  filterFromPreset,
  createLook,
  applyLook,
  lookMatches,
  parseLooks,
  autoEnhance,
  type FilterPreset,
  type FilterCategory,
  type Look,
  type AutoEnhanceResult,

  /* Rendering and export */
  renderImage,
  exportImage,
  renderToCanvas,
  type ExportOptions,
  type ExportResult,
  type ExportMimeType,
  type RenderedCanvas,
  type RendererKind,

  /* The editor store (UI-independent state + undo history) */
  TOOL_IDS,
  createEditorStore,
  selectCanUndo,
  selectCanRedo,
  selectIsDirty,
  type CreateEditorStoreOptions,
  type EditorStore,
  type EditorStoreState,
  type EditorState,
  type EditorActions,
  type EditorStatus,
  type EditorTask,
  type EditRecipe,
  type ChangeOptions,
  type TaskContext,
  type ToolId,
  type History,
  type HistoryEntry,
  type Viewport,
  type ViewportChangeOptions,
  type CropView,
} from './internal';
