import { describe, expect, it } from 'vitest';
import { computeAutoEnhance, computeHistogram, percentile } from './analyze';

/** A synthetic image: `n` pixels generated by `fn(i)` → [r, g, b] in 0…255. */
function image(n: number, fn: (i: number) => [number, number, number]): Uint8ClampedArray {
  const data = new Uint8ClampedArray(n * 4);
  for (let i = 0; i < n; i++) {
    const [r, g, b] = fn(i);
    data.set([r, g, b, 255], i * 4);
  }
  return data;
}

describe('analysis', () => {
  it('histogram percentiles', () => {
    const data = image(256, (i) => [i, i, i]);
    const hist = computeHistogram(data);
    expect(hist.total).toBe(256);
    expect(percentile(hist.luma, hist.total, 0.5)).toBeCloseTo(0.5, 1);
  });

  it('auto-enhance stretches a flat, dark, blue-tinted image', () => {
    // Values between ~40 and ~150, with a blue cast.
    const data = image(4000, (i) => {
      const v = 40 + (i % 110);
      return [v * 0.85, v * 0.95, Math.min(255, v * 1.2)];
    });
    const { levels, finetune } = computeAutoEnhance(data);
    expect(levels.black).toBeGreaterThan(0.05);
    expect(levels.white).toBeLessThan(0.95);
    expect(finetune.temperature).toBeGreaterThan(0.1); // warms up the blue cast
    expect(finetune.contrast).toBeGreaterThanOrEqual(0);
  });

  it('leaves a well-exposed neutral image nearly alone', () => {
    const data = image(4096, (i) => {
      const v = Math.round((i / 4095) * 255);
      return [v, v, v];
    });
    const { levels, finetune } = computeAutoEnhance(data);
    expect(levels.black).toBe(0);
    expect(levels.white).toBe(1);
    expect(Math.abs(finetune.temperature)).toBeLessThan(0.05);
    expect(Math.abs(levels.mid)).toBeLessThan(0.15);
  });
});
